services:
  peer1:
    image: bgpgg/bgpgg:smoke-test
    configs:
      - source: peer1_config
        target: /etc/bgpgg/config.yaml
    networks:
      smoke_net:
        ipv4_address: 172.30.0.10

  peer2:
    image: bgpgg/bgpgg:smoke-test
    configs:
      - source: peer2_config
        target: /etc/bgpgg/config.yaml
    networks:
      smoke_net:
        ipv4_address: 172.30.0.20

configs:
  peer1_config:
    content: |
      asn: 65001
      router_id: 1.1.1.1

  peer2_config:
    content: |
      asn: 65002
      router_id: 2.2.2.2

networks:
  smoke_net:
    ipam:
      config:
        - subnet: 172.30.0.0/16
