services:
  peer1:
    image: bgpgg/bgpgg:smoke-test
    container_name: bgpgg-smoke-peer1
    hostname: peer1
    configs:
      - source: peer1_config
        target: /etc/bgpgg/config.yaml
    networks:
      smoke_net:
        ipv4_address: 172.30.0.10
    healthcheck:
      test: ["CMD", "bgpgg", "--addr", "http://127.0.0.1:50051", "global", "info"]
      interval: 1s
      timeout: 1s
      retries: 10

  peer2:
    image: bgpgg/bgpgg:smoke-test
    container_name: bgpgg-smoke-peer2
    hostname: peer2
    configs:
      - source: peer2_config
        target: /etc/bgpgg/config.yaml
    networks:
      smoke_net:
        ipv4_address: 172.30.0.20
    healthcheck:
      test: ["CMD", "bgpgg", "--addr", "http://127.0.0.1:50051", "global", "info"]
      interval: 1s
      timeout: 1s
      retries: 10

configs:
  peer1_config:
    content: |
      asn: 65001
      router_id: 1.1.1.1
      listen_address: "0.0.0.0:179"
      grpc_listen_address: "0.0.0.0:50051"
      peers:
        - address: "172.30.0.20:179"

  peer2_config:
    content: |
      asn: 65002
      router_id: 2.2.2.2
      listen_address: "0.0.0.0:179"
      grpc_listen_address: "0.0.0.0:50051"
      peers:
        - address: "172.30.0.10:179"

networks:
  smoke_net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.30.0.0/16
