name: Tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup dependencies
      run: make setup

    - name: Run tests
      run: make test

    - name: Run system tests
      run: make systest

    - name: Run Linux system tests
      run: make systest-linux

  loadtest:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup dependencies
      run: make setup

    - name: Run load tests
      run: make loadtest

  bsd:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - uses: vmactions/freebsd-vm@v1
      with:
        usesh: true
        copyback: false
        mem: 8192
        prepare: |
          ./script/setup-freebsd.sh
        run: |
          gmake test
          gmake systest
